# Generated by Django 5.0.7 on 2024-08-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('it', 'it'), ('Mobile', 'Mobile'), ('non It ', 'Non It')], max_length=50)),
            ],
        ),
    ]
