# Generated by Django 4.2.1 on 2024-08-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company1',
            fields=[
                ('comapany1_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('about', models.TextField()),
            ],
        ),
    ]
