# Generated by Django 4.2.1 on 2024-08-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_employee1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee1',
            old_name='address1',
            new_name='address',
        ),
    ]
